"""
Committee packet: one docx per plan and product, generated by the build
=========================================================================
The packet is what a committee reads before the memo: a one-page summary
of both liquidity verdicts, the benchmark state, the flags the record
raises, coverage and verification counts, then exhibits drawn from the
same artifacts the site and the memo read (benchmark selection with its
rejection ledger, the liquidity match for this plan, the typed fee row,
the cohort placement) and a provenance page. Nothing here is computed
anew: every figure is a cited cell, a typed projection of one, or an
engine artifact. The decision memo stays a separate document.

    python src/tark_packet.py [--out DIR]  -> DIR/<plan>__<product>_committee_packet.docx
"""
from __future__ import annotations

import json
from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt

from tark_data import (ADVISOR_NOT_EVIDENCE, ADVISOR_STATED_CELLS, DATA, RULE, RULE_CITATION,
                       coverage_summary, load_advisor, load_plan, load_products, plan_keys,
                       record_as_of, status_kind)
from tark_display import RUBRIC_LABEL, display_path_free, facts_by_cell, typed_headline
from tark_memo import (KIND_ORDER, SITE_MEMOS, _fill, _flags, _liquidity_section, _save,
                       _set_letter, cell_title)

FEE_CELLS = ("2.1", "2.2", "2.3", "2.4", "2.6", "2.7", "6.4")


def _stat_line(comp: dict) -> str:
    """The comparison's statistic named for its comparator (rule 12)."""
    if comp.get("kind") == "composite":
        return (f"relative wealth ratio {comp['relative_wealth_ratio']} vs the peer composite, annualized "
                f"excess return {comp['excess_return_pct']}%/yr (not a public market equivalent)")
    return f"KS-PME {comp['ks_pme']}, Direct Alpha {comp['direct_alpha_pct']}%/yr"


def packet_name(plan_key: str, key: str) -> str:
    return f"{plan_key}__{key}_committee_packet.docx"


def build_packet(key: str, plan_key: str, out_dir: Path | None = None) -> Path:
    p = load_products()[key]
    plan = load_plan(plan_key)
    sel_path = DATA / "benchmarks" / f"{key}_selection.json"
    sel = json.loads(sel_path.read_text()) if sel_path.exists() else None
    mp = DATA / "liquidity" / f"{plan_key}__{key}_match.json"
    m = json.loads(mp.read_text()) if mp.exists() else None
    fp = DATA / "facts" / f"{key}.json"
    fdoc = json.loads(fp.read_text()) if fp.exists() else {}
    fbc = facts_by_cell(fdoc.get("facts", {}))
    cov = coverage_summary(key)
    adv = (load_advisor(plan_key, key) or {}).get("cells") or {}

    doc = Document()
    _set_letter(doc)
    doc.styles["Normal"].font.size = Pt(10.5)
    doc.add_heading("Committee packet", level=0)
    head = doc.add_paragraph()
    head.add_run(f"Plan: {plan['display_label']}\n").bold = True
    head.add_run(f"Product: {p['fund_name']} ({p['wrapper']}, CIK {p['cik']})\n")
    head.add_run(f"Record as of {record_as_of()}. DRAFT, generated by the build from the record. "
                 "The decision memo for the same plan and product is a separate document.")

    # ---- one-page summary
    doc.add_heading("Summary", level=1)
    if m:
        doc.add_paragraph(f"Structural liquidity verdict: {m['verdict'].upper()} (typed facts, plan-independent). "
                          f"Scenario verdict under this plan (ILLUSTRATIVE, default sliders): "
                          f"{(m.get('scenario_verdict') or 'not computable').upper()}.")
    if sel is None:
        doc.add_paragraph("Benchmark: no selection artifact.")
    elif sel.get("escalation"):
        doc.add_paragraph("Benchmark: escalated. " + sel["escalation"])
    else:
        pr = sel["primary"]
        comp = pr.get("comparison") or {}
        line = f"Benchmark: {pr['candidate']} at {pr['score']}/{pr['max']}"
        if comp:
            line += f", {_stat_line(comp)} over {comp['window']}"
        doc.add_paragraph(line + ".")
    flags = _flags(sel, m, fdoc)
    doc.add_paragraph("Flags raised by the record (each restates a typed value or verdict, with its source):")
    for f in flags or ["none"]:
        doc.add_paragraph(f, style="List Bullet")
    doc.add_paragraph(f"Evidence coverage: {cov['headline']}. Verified by a person: {cov['verified']}. "
                      f"Advisor-stated inputs for this plan: {len(adv)} of {len(ADVISOR_STATED_CELLS)}.")
    doc.add_paragraph("The committee makes the decision on this record. This packet does not decide.")

    # ---- exhibit A: benchmark selection
    doc.add_heading("Exhibit A. Benchmark selection and rejection ledger", level=1)
    if sel is None:
        doc.add_paragraph("No selection artifact for this product.")
    else:
        doc.add_paragraph(f"{RUBRIC_LABEL[0].upper()}{RUBRIC_LABEL[1:]}, threshold 7 of 12, strategy gate. "
                          + (f"Max attainable on held data {sel['max_attainable']}/12." if sel.get("max_attainable") is not None
                             else "No candidate is eligible on held data."))
        t = doc.add_table(rows=1, cols=4)
        t.style = "Table Grid"
        h = t.rows[0].cells
        h[0].text, h[1].text, h[2].text, h[3].text = "Slot", "Candidate", "Score", "Outcome"
        for slot in ("primary", "secondary"):
            s2 = sel.get(slot)
            if s2:
                r = t.add_row().cells
                comp = s2.get("comparison") or {}
                r[0].text, r[1].text, r[2].text = slot, s2["candidate"], f"{s2['score']}/{s2['max']}"
                r[3].text = (f"{_stat_line(comp)}, {comp['window']}"
                             if comp else (s2.get("comparison_note") or sel.get("comparison_note") or "selected"))
        for rj in sel.get("rejected", []):
            r = t.add_row().cells
            r[0].text, r[1].text, r[2].text, r[3].text = "rejected", rj["candidate"], f"{rj['score']}/{rj['max']}", rj["rejection"]
        for row in t.rows:
            row.cells[0].width, row.cells[1].width, row.cells[2].width, row.cells[3].width = Inches(0.8), Inches(2.4), Inches(0.6), Inches(2.7)

    # ---- exhibit B: liquidity match for this plan (the memo's section, verbatim)
    doc.add_heading("Exhibit B. Liquidity match for this plan", level=1)
    _liquidity_section(doc, m, fdoc, plan)

    # ---- exhibit C: the typed fee row
    doc.add_heading("Exhibit C. Fees and terms, typed layer", level=1)
    doc.add_paragraph("Each line is the typed fact that cites the cell, or the cell's status word when no "
                      "fact is typed. Full text and provenance are in the record.")
    t = doc.add_table(rows=1, cols=3)
    t.style = "Table Grid"
    h = t.rows[0].cells
    h[0].text, h[1].text, h[2].text = "Cell", "Typed headline", "Status"
    for cid in FEE_CELLS:
        c = p["cells"][cid]
        r = t.add_row().cells
        r[0].text = f"{cid} {cell_title(cid)}"
        r[1].text = typed_headline(cid, fbc.get(cid, {})) or ("n/a" if status_kind(c.get("status", "")) == "n/a"
                                                               else "no typed fact for this cell")
        r[2].text = str(c.get("status", ""))
    for row in t.rows:
        row.cells[0].width, row.cells[1].width, row.cells[2].width = Inches(2.0), Inches(2.5), Inches(2.0)

    # ---- exhibit D: cohort placement
    doc.add_heading("Exhibit D. Peer cohort placement", level=1)
    cid = fdoc.get("cohort_id")
    cpath = DATA / "cohorts" / f"{cid}.json" if cid else None
    if cpath and cpath.exists():
        co = json.loads(cpath.read_text())
        doc.add_paragraph(f"Cohort {co['label']} (n={co['n']}). {fdoc.get('membership_rationale', '')}")
        v29 = p["cells"]["2.9"].get("value")
        if v29:
            doc.add_paragraph(display_path_free(v29))
        for cv in co.get("caveats", []):
            doc.add_paragraph(cv, style="List Bullet")
    else:
        doc.add_paragraph("No cohort artifact for this product.")

    # ---- advisor inputs and provenance
    doc.add_heading("Advisor-stated inputs (this plan)", level=1)
    doc.add_paragraph(ADVISOR_NOT_EVIDENCE)
    if adv:
        for c2 in ADVISOR_STATED_CELLS:
            e = adv.get(c2)
            if e:
                doc.add_paragraph(f"{c2} {cell_title(c2)}: {e['value']} (stated by {e['signer']} on {e['date']})")
    else:
        doc.add_paragraph(f"None stated for {plan['display_label']}.")
    doc.add_heading("Provenance", level=1)
    doc.add_paragraph("Cell status for this product: " + ", ".join(f"{label} {cov[k]}" for k, label in KIND_ORDER) + ".")
    doc.add_paragraph(f"Regulatory basis: {RULE_CITATION}, paragraphs {RULE['paragraphs']}, cited not paraphrased. "
                      f"Every figure above is a cited cell, a typed projection of one, or an engine artifact of the "
                      f"record as of {record_as_of()}. Scenario figures are ILLUSTRATIVE. The plan is shown "
                      "under its anonymized label.")

    out = out_dir or SITE_MEMOS
    out.mkdir(parents=True, exist_ok=True)
    path = out / packet_name(plan_key, key)
    _save(doc, path)
    return path


def write_all_packets(out_dir: Path | None = None) -> list[Path]:
    out = out_dir or SITE_MEMOS
    out.mkdir(parents=True, exist_ok=True)
    for stale in out.glob("*_committee_packet.docx"):
        stale.unlink()
    return [build_packet(key, pl, out) for pl in plan_keys() for key in load_products()]


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    paths = write_all_packets(Path(a.out) if a.out else None)
    print(f"wrote {len(paths)} packets to {paths[0].parent}")
